### ISSUE TITLE
discord request 

### ISSUE THREAD

**Issue by EmekaSenpai** [N0rz3/Inspector#2]
hello,  I sent u a request on discord to be able to reach out to about a problem,  I didn't know if u would accept so I decided to use this means.

**Comment by N0rz3** [comment]
hi so for discord I think I'm going to remove the possibility of contacting me because at the moment I've had a dozen msg to help so tell me your problem via this chat please

**Comment by N0rz3** [comment]
just if the problem has in report with the requirements or your phone number is not french please search alone because the tool is said mainly for French numbers so if your question is related to these examples search alone and modify the code as for example in the ignorant modules you will have to remove the "33" by the country code of the number and that goes for the other things where there is marked "fr"

**Comment by EmekaSenpai** [comment]
thank you very much , I am sorry for responding late ,Yes that was what I
wanted to ask if I could search for other number like Philippines,  I will
try what u suggested and give u feedback. but also there so many sites that
claim when u pay a certain amount , u will have access to the information
about the number, I inputed in , are most of them scams?

**Comment by N0rz3** [comment]
frankly I don't really have an opinion for this kind of site after you have to check if the site used for the research is reliable, if it is known or not. For me it's always better to do searches like this for example (telephone number) with tools, open sources like this tool (inspector) or even Osint Industries which is very useful and if you really need more information can be the pay for more results. So in summary, I remain more-early mixed on that
